import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { inter, rubik } from "@/ui/fonts";
import Link from "next/link";
import Navbar from "@/ui/component/Navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			{/* <body className={inter.className}>{children}</body> */}
			<body className={`${rubik.className} antialiased`}>
				<nav>
					<Navbar></Navbar>
				</nav>
				{children}
			</body>
		</html>
	);
}
